spring:
  application:
    name: servicio-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Registro-Contable/configuration-repository.git
          default-label: main
          repos:
#            local:
#              uri: ${user.home}/RegistroContableConfigRepo
#              pattern:
#                - '*/local'
#              default-label: develop
            development:
              uri: https://github.com/Registro-Contable/configuration-repository.git
              pattern:
                - '*/development'
                - '*/staging'
              default-label: develop
            staging:
              pattern:
                - '*/qa'
                - '*/production'
              uri: https://github.com/Registro-Contable/configuration-repository.git
    
server:
  port: 8888
