name: Create release workflow

#on: [workflow_dispatch]
on:
  push:
    branches:
      - 'develop'

jobs:
  create-release:
    name: Create release branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
#          server-id: github
      - name: Prepare
        id: prep
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo ::set-output name=version::${VERSION}
#      - name: Create release with Maven
#        run: mvn -B release:branch
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}