name: Create release workflow

on: [workflow_dispatch]

jobs:
  create-release:
    name: Create release branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          server-id: github
      - name: Create release with Maven
        run: mvn -B release:branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}